# Name of the GitHub Action as it will appear in the Actions marketplace or workflow UI
name: "Open a Github Issue (nk)"

# Author name (shown in GitHub marketplace or when inspecting the action)
author: nikitaks97

# Short description of what this Action does
description: "Opens a github issue"

# Define input parameters that the Action accepts
inputs:
  token: # Input key that represents a GitHub token (used for authentication)
    description: "Github Token"
    required: true # This input must be provided for the Action to run

  title: # Input for the issue's title
    description: "Issue Title"
    required: true

  body: # Optional input for the issue's body/description
    description: "Issue Body"

  assignees: # Optional input for assigning the issue to users (newline-separated list)
    description: "Issue Assignees"

# Define the outputs from this Action that can be used in later steps
outputs:
  issue: # The output variable's name
    description: "The issue object as a json string" # Describes what this output contains

# Define how this Action should be executed
runs:
  using: "node16" # Tells GitHub to run the action using Node.js 16 runtime
  main: "dist/index.js" # The entry point of the compiled action (usually compiled from TypeScript)

# Optional branding metadata (used in GitHub Marketplace UI)
branding:
  icon: "alert-circle" # Icon shown in Marketplace (from Feather icons)
  color: "yellow"      # Color theme for the action badge
